# Generated by Django 4.1.3 on 2022-11-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Singer',
            new_name='Singers',
        ),
    ]
