# Generated by Django 4.1.3 on 2022-11-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_singer_singers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Albums',
            new_name='Album',
        ),
        migrations.RenameModel(
            old_name='Singers',
            new_name='Singer',
        ),
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
